"use client";
import{useState}from"react";
type K="image-compressor"|"image-resizer"|"jpg-to-pdf"|"pdf-to-jpg"|"compress-pdf"|"merge-pdf"|"image-converter"|"image-cropper";
const cfg:Record<K,{t:string;d:string;a:string;m?:boolean}>={"image-compressor":{t:"Image Compressor",d:"Compress JPG, PNG and WebP images in your browser.",a:"image/jpeg,image/png,image/webp"},"image-resizer":{t:"Image Resizer",d:"Resize an image to exact dimensions.",a:"image/jpeg,image/png,image/webp"},"jpg-to-pdf":{t:"JPG to PDF",d:"Convert one or more images into a single PDF.",a:"image/jpeg,image/png,image/webp",m:true},"pdf-to-jpg":{t:"PDF to JPG",d:"Convert PDF pages into JPG images.",a:"application/pdf"},"compress-pdf":{t:"Compress PDF",d:"Reduce PDF size by rebuilding its pages.",a:"application/pdf"},"merge-pdf":{t:"Merge PDF",d:"Combine multiple PDF files into one.",a:"application/pdf",m:true},"image-converter":{t:"JPG PNG WebP Converter",d:"Convert images between JPG, PNG and WebP.",a:"image/jpeg,image/png,image/webp"},"image-cropper":{t:"Image Cropper",d:"Crop an image and download the result.",a:"image/jpeg,image/png,image/webp"}};
function dl(b:Blob,n:string){const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function read(f:File){return new Promise<HTMLImageElement>((ok,no)=>{const i=new Image(),u=URL.createObjectURL(f);i.onload=()=>{URL.revokeObjectURL(u);ok(i)};i.onerror=()=>no(Error("Could not read image."));i.src=u})}
function blob(c:HTMLCanvasElement,t:string,q?:number){return new Promise<Blob>((ok,no)=>c.toBlob(b=>b?ok(b):no(Error("Could not create file.")),t,q))}async function pdfLib(){if(!(window as any).PDFLib){await new Promise<void>((ok,no)=>{const s=document.createElement("script");s.src="https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/dist/pdf-lib.min.js";s.onload=()=>ok();s.onerror=()=>no(Error("PDF library failed to load."));document.head.appendChild(s)})}if(!(window as any).PDFLib)throw Error("PDF library unavailable.");return (window as any).PDFLib}
export default function ToolClient({tool}:{tool:K}){const c=cfg[tool];const[files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[w,setW]=useState(1200),[h,setH]=useState(800),[q,setQ]=useState(75),[fmt,setFmt]=useState("image/jpeg"),[crop,setCrop]=useState({x:0,y:0,w:800,h:600});
async function run(){if(!files.length)return setMsg("Choose a file first.");setBusy(true);setMsg("");try{
if(tool==="image-compressor"){const i=await read(files[0]),x=document.createElement("canvas");x.width=i.naturalWidth;x.height=i.naturalHeight;x.getContext("2d")!.drawImage(i,0,0);const t=files[0].type==="image/png"?"image/webp":files[0].type,b=await blob(x,t,q/100);dl(b,"vidzora-compressed."+t.split("/")[1].replace("jpeg","jpg"))}
else if(tool==="image-resizer"){const i=await read(files[0]),x=document.createElement("canvas");x.width=Math.max(1,w);x.height=Math.max(1,h);x.getContext("2d")!.drawImage(i,0,0,x.width,x.height);dl(await blob(x,files[0].type==="image/png"?"image/png":"image/jpeg",.9),"vidzora-resized."+(files[0].type==="image/png"?"png":"jpg"))}
else if(tool==="image-converter"){const i=await read(files[0]),x=document.createElement("canvas");x.width=i.naturalWidth;x.height=i.naturalHeight;x.getContext("2d")!.drawImage(i,0,0);dl(await blob(x,fmt,.92),"vidzora-converted."+fmt.split("/")[1].replace("jpeg","jpg"))}
else if(tool==="image-cropper"){const i=await read(files[0]),x=Math.max(0,Math.min(crop.x,i.naturalWidth-1)),y=Math.max(0,Math.min(crop.y,i.naturalHeight-1)),ww=Math.max(1,Math.min(crop.w,i.naturalWidth-x)),hh=Math.max(1,Math.min(crop.h,i.naturalHeight-y)),z=document.createElement("canvas");z.width=ww;z.height=hh;z.getContext("2d")!.drawImage(i,x,y,ww,hh,0,0,ww,hh);dl(await blob(z,"image/png"),"vidzora-crop.png")}
else if(tool==="jpg-to-pdf"){const P=await pdfLib();const d=await P.PDFDocument.create();for(const f of files){const b=new Uint8Array(await f.arrayBuffer());const im=f.type==="image/png"?await d.embedPng(b):await d.embedJpg(b);const p=d.addPage([im.width,im.height]);p.drawImage(im,{x:0,y:0,width:im.width,height:im.height})}dl(new Blob([await d.save()],{type:"application/pdf"}),"vidzora-images.pdf")}else if(tool==="merge-pdf"||tool==="compress-pdf"){const P=await pdfLib();const d=await P.PDFDocument.create();for(const f of files){const s=await P.PDFDocument.load(await f.arrayBuffer(),{ignoreEncryption:true});const ps=await d.copyPages(s,s.getPageIndices());ps.forEach((p:any)=>d.addPage(p))}dl(new Blob([await d.save({useObjectStreams:true,addDefaultPage:false})],{type:"application/pdf"}),tool==="merge-pdf"?"vidzora-merged.pdf":"vidzora-compressed.pdf")}else if(tool==="pdf-to-jpg"){const P=await import(/* webpackIgnore: true */"https://cdn.jsdelivr.net/npm/pdfjs-dist@5.4.149/build/pdf.min.mjs");P.GlobalWorkerOptions.workerSrc="https://cdn.jsdelivr.net/npm/pdfjs-dist@5.4.149/build/pdf.worker.min.mjs";const d=await P.getDocument({data:new Uint8Array(await files[0].arrayBuffer())}).promise;for(let n=1;n<=d.numPages;n++){const p=await d.getPage(n),v=p.getViewport({scale:1.5}),x=document.createElement("canvas");x.width=v.width;x.height=v.height;await p.render({canvasContext:x.getContext("2d")!,viewport:v}).promise;dl(await blob(x,"image/jpeg",.9),"vidzora-page-"+n+".jpg")}}
setMsg("Done — your file is ready.");}catch(e:any){setMsg(e?.message||"Could not process this file.")}finally{setBusy(false)}}
return <main className="toolShell"><header className="nav"><a className="brand" href="/">Vidzora<span>•</span></a><nav><a href="/tools">All tools</a><a href="/">Downloader</a></nav></header><section className="toolHero"><div className="eyebrow">Vidzora FREE TOOL</div><h1>{c.t}</h1><p>{c.d}</p><div className="toolBox"><label className="dropZone"><input type="file" accept={c.a} multiple={!!c.m} onChange={e=>{setFiles(Array.from(e.target.files||[]));setMsg("")}}/><strong>{files.length?files.length+" file(s) selected":"Choose file"+(c.m?"s":"")}</strong><span>Tap to browse or select from your device</span></label>
{tool==="image-compressor"&&<label className="control">Quality <input type="range" min="20" max="95" value={q} onChange={e=>setQ(+e.target.value)}/><b>{q}%</b></label>}
{tool==="image-resizer"&&<div className="controls2"><label>Width<input type="number" value={w} onChange={e=>setW(+e.target.value)}/></label><label>Height<input type="number" value={h} onChange={e=>setH(+e.target.value)}/></label></div>}
{tool==="image-converter"&&<label className="control">Output<select value={fmt} onChange={e=>setFmt(e.target.value)}><option value="image/jpeg">JPG</option><option value="image/png">PNG</option><option value="image/webp">WebP</option></select></label>}
{tool==="image-cropper"&&<div className="controls2"><label>X<input type="number" value={crop.x} onChange={e=>setCrop({...crop,x:+e.target.value})}/></label><label>Y<input type="number" value={crop.y} onChange={e=>setCrop({...crop,y:+e.target.value})}/></label><label>Width<input type="number" value={crop.w} onChange={e=>setCrop({...crop,w:+e.target.value})}/></label><label>Height<input type="number" value={crop.h} onChange={e=>setCrop({...crop,h:+e.target.value})}/></label></div>}
<button className="toolRun" disabled={busy} onClick={run}>{busy?"Processing…":"Process & Download"}</button>{msg&&<div className="toolMessage">{msg}</div>}</div><div className="toolTrust"><b>✓ Simple</b><b>✓ Mobile friendly</b><b>✓ No account</b></div></section></main>}